### PR TITLE
Rare and treasure fixes

### PR DESCRIPTION
**Pull request by NLZ**
Adding #1 and kemayo/wow-silverdragon#3, plus a lot of other stuff I found generally in Vol'dun.
Added [Scavenger of the Sands](https://www.wowhead.com/achievement=13016/scavenger-of-the-sands), not sure if it fits the addon's profile.

### CODE REVIEW

**Comment by kemayo** [comment]
I'll take a bunch of this on faith, I admit!

**Comment by NLZ** [comment]
A lot of Vol'dun rares had wrong quest id, I guess it was incorrect on wowhead. I see they are no longer listed on the achievement page.
Also I got repeating quest ids for junk treasure chests in the same area, I guess thats how they works.
But Vol'dun is clearing up nicely.

**Comment by kemayo** [comment]
Yeah, junk chests are working like the Argus ones did. There's a pool of chests in an area all attached to a questid, so you can loot one from that subzone and then you have to move on for the day.

**Comment by NLZ** [comment]
By the way I left in a few commented out path() for rares, as the function is not defined there. I leave it up to you if you want to implement it and how.
Also how can I get the criterias for an achievement? Asking to fill out Scavenger of the Sands.

**Comment by kemayo** [comment]
Technically you could fiddle with the API in game -- it's one of the returns from `GetAchievementCriteriaInfo(achievementid, i)`. I just use [idTip](https://www.curseforge.com/wow/addons/idtip), though, which adds it to the tooltip in the achievement window.

**Comment by kemayo** [comment]
Oh, also, `path` is accessible there via `ns.path`.

**Comment by NLZ** [comment]
Thank you.
One more if I may, how to find atlas icons? Aside from extracting the game files and browsing until I find something nice.

**Comment by kemayo** [comment]
I mostly use a combination of browsing [AtlasInfo.lua on TownlongYak](https://www.townlong-yak.com/framexml/live/Helix/AtlasInfo.lua) and my [TextureViewer](https://www.wowace.com/projects/textureviewer) addon.

I've adjusted `path` in f2d0555 so it can do junk stuff.

**Pull request merged**
